//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by cswinrt.exe version 2.2.0.241111.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using WinRT;
using WinRT.Interop;


#pragma warning disable 0169 // warning CS0169: The field '...' is never used
#pragma warning disable 0649 // warning CS0169: Field '...' is never assigned to
#pragma warning disable CA2207, CA1063, CA1033, CA1001, CA2213

namespace Automerge.Windows
{
    [global::WinRT.WindowsRuntimeType("Automerge.Windows")]
    [global::WinRT.WindowsRuntimeHelperType(typeof(global::ABI.Automerge.Windows.Document))]
    [global::ABI.Automerge.Windows.DocumentRcwFactory]
    [global::WinRT.ProjectedRuntimeClass(typeof(IDocument))]
    public sealed class Document : global::System.Runtime.InteropServices.ICustomQueryInterface, IWinRTObject, IEquatable<Document>
    {
        private IntPtr ThisPtr => _inner == null ? (((IWinRTObject)this).NativeObject).ThisPtr : _inner.ThisPtr;

        private readonly IObjectReference _inner = null;



        private IObjectReference _objRef_global__Automerge_Windows_IDocument => _inner;


        private static volatile IObjectReference ___objRef_global__Automerge_Windows_Document;
        private static IObjectReference _objRef_global__Automerge_Windows_Document
        {
            get
            { 
                var factory = ___objRef_global__Automerge_Windows_Document;
                if (factory != null && factory.IsInCurrentContext)
                {
                    return factory;
                }
                else
                {
                    return ___objRef_global__Automerge_Windows_Document = ActivationFactory.Get("Automerge.Windows.Document");
                }
            }
        }

        public Document() 
        {
            _inner = global::ABI.WinRT.Interop.IActivationFactoryMethods.ActivateInstanceUnsafe(_objRef_global__Automerge_Windows_Document, global::ABI.Automerge.Windows.IDocumentMethods.IID);
            ComWrappersSupport.RegisterObjectForInterface(this, ThisPtr);
            ComWrappersHelper.Init(_inner, false);

        }

        public static I As<I>() => ActivationFactory.Get("Automerge.Windows.Document").AsInterface<I>();

        private static volatile IObjectReference ___objRef_global__Automerge_Windows_IDocumentStatics;
        private static IObjectReference _objRef_global__Automerge_Windows_IDocumentStatics
        {
            get
            { 
                var factory = ___objRef_global__Automerge_Windows_IDocumentStatics;
                if (factory != null && factory.IsInCurrentContext)
                {
                    return factory;
                }
                else
                {
                    return ___objRef_global__Automerge_Windows_IDocumentStatics = ActivationFactory.Get("Automerge.Windows.Document", global::ABI.Automerge.Windows.IDocumentStaticsMethods.IID);
                }
            }
        }

        public static Document Load(global::Windows.Storage.Streams.IBuffer data) => global::ABI.Automerge.Windows.IDocumentStaticsMethods.Load(_objRef_global__Automerge_Windows_IDocumentStatics, data);

        public static Document FromAbi(IntPtr thisPtr)
        {
            if (thisPtr == IntPtr.Zero) return null;
            return MarshalInspectable<Document>.FromAbi(thisPtr);
        }

        internal Document(IObjectReference objRef)
        {
            _inner = objRef.As(global::ABI.Automerge.Windows.IDocumentMethods.IID);

        }


        public static bool operator ==(Document x, Document y) => (x?.ThisPtr ?? IntPtr.Zero) == (y?.ThisPtr ?? IntPtr.Zero);
        public static bool operator !=(Document x, Document y) => !(x == y);
        public bool Equals(Document other) => this == other;
        public override bool Equals(object obj) => obj is Document that && this == that;
        public override int GetHashCode() => ThisPtr.GetHashCode();


        bool IWinRTObject.HasUnwrappableNativeObject => true;
        IObjectReference IWinRTObject.NativeObject => _inner;
        private volatile global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, IObjectReference> _queryInterfaceCache;
        private global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, IObjectReference> MakeQueryInterfaceCache()
        {
            global::System.Threading.Interlocked.CompareExchange(ref _queryInterfaceCache, new global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, IObjectReference>(), null); 
            return _queryInterfaceCache;
        }
        global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, IObjectReference> IWinRTObject.QueryInterfaceCache => _queryInterfaceCache ?? MakeQueryInterfaceCache();
        private volatile global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, object> _additionalTypeData;
        private global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, object> MakeAdditionalTypeData()
        {
            global::System.Threading.Interlocked.CompareExchange(ref _additionalTypeData, new global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, object>(), null); 
            return _additionalTypeData;
        }
        global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, object> IWinRTObject.AdditionalTypeData => _additionalTypeData ?? MakeAdditionalTypeData();

        private struct InterfaceTag<I>{};


        public global::Windows.Storage.Streams.IBuffer Save() => global::ABI.Automerge.Windows.IDocumentMethods.Save(_objRef_global__Automerge_Windows_IDocument);

        public global::Windows.Storage.Streams.IBuffer GetHeads() => global::ABI.Automerge.Windows.IDocumentMethods.GetHeads(_objRef_global__Automerge_Windows_IDocument);

        public global::Windows.Storage.Streams.IBuffer GetChanges(global::Windows.Storage.Streams.IBuffer heads) => global::ABI.Automerge.Windows.IDocumentMethods.GetChanges(_objRef_global__Automerge_Windows_IDocument, heads);

        public void ApplyChanges(global::Windows.Storage.Streams.IBuffer changes) => global::ABI.Automerge.Windows.IDocumentMethods.ApplyChanges(_objRef_global__Automerge_Windows_IDocument, changes);

        public void Merge(Document other) => global::ABI.Automerge.Windows.IDocumentMethods.Merge(_objRef_global__Automerge_Windows_IDocument, other);

        public string GetValue(string pathJson) => global::ABI.Automerge.Windows.IDocumentMethods.GetValue(_objRef_global__Automerge_Windows_IDocument, pathJson);

        public void PutJsonRoot(string jsonObj) => global::ABI.Automerge.Windows.IDocumentMethods.PutJsonRoot(_objRef_global__Automerge_Windows_IDocument, jsonObj);

        private bool IsOverridableInterface(Guid iid) => false;

        global::System.Runtime.InteropServices.CustomQueryInterfaceResult global::System.Runtime.InteropServices.ICustomQueryInterface.GetInterface(ref Guid iid, out IntPtr ppv)
        {
            ppv = IntPtr.Zero;
            if (IsOverridableInterface(iid) || global::WinRT.Interop.IID.IID_IInspectable == iid)
            {
                return global::System.Runtime.InteropServices.CustomQueryInterfaceResult.NotHandled;
            }

            if (((IWinRTObject)this).NativeObject.TryAs(iid, out ppv) >= 0)
            {
                return global::System.Runtime.InteropServices.CustomQueryInterfaceResult.Handled;
            }

            return global::System.Runtime.InteropServices.CustomQueryInterfaceResult.NotHandled;
        }
    }
    [global::WinRT.WindowsRuntimeType("Automerge.Windows")][Guid("2138D060-E4F9-5C86-B4D5-28386991F7AA")][global::WinRT.WindowsRuntimeHelperType(typeof(global::ABI.Automerge.Windows.IDocument))]
    internal interface IDocument
    {
        global::Windows.Storage.Streams.IBuffer Save();
        global::Windows.Storage.Streams.IBuffer GetHeads();
        global::Windows.Storage.Streams.IBuffer GetChanges(global::Windows.Storage.Streams.IBuffer heads);
        void ApplyChanges(global::Windows.Storage.Streams.IBuffer changes);
        void Merge(Document other);
        string GetValue(string pathJson);
        void PutJsonRoot(string jsonObj);
    }
    [global::WinRT.WindowsRuntimeType("Automerge.Windows")][Guid("2F43CE15-B36B-5C5B-B80E-660448DD5119")][global::WinRT.WindowsRuntimeHelperType(typeof(global::ABI.Automerge.Windows.IDocumentStatics))]
    internal interface IDocumentStatics
    {
        Document Load(global::Windows.Storage.Streams.IBuffer data);
    }
    [global::WinRT.WindowsRuntimeType("Automerge.Windows")][Guid("60BC0E03-0113-512F-AEAC-5D1AE542AE95")][global::WinRT.WindowsRuntimeHelperType(typeof(global::ABI.Automerge.Windows.ISyncState))]
    internal interface ISyncState
    {
        global::Windows.Storage.Streams.IBuffer GenerateSyncMessage(Document doc);
        void ReceiveSyncMessage(Document doc, global::Windows.Storage.Streams.IBuffer message);
        global::Windows.Storage.Streams.IBuffer Save();
    }
    [global::WinRT.WindowsRuntimeType("Automerge.Windows")][Guid("BAEF2164-C763-5CDF-B0DB-883CD761B6CC")][global::WinRT.WindowsRuntimeHelperType(typeof(global::ABI.Automerge.Windows.ISyncStateStatics))]
    internal interface ISyncStateStatics
    {
        SyncState Load(global::Windows.Storage.Streams.IBuffer data);
    }
    [global::WinRT.WindowsRuntimeType("Automerge.Windows")]
    [global::WinRT.WindowsRuntimeHelperType(typeof(global::ABI.Automerge.Windows.SyncState))]
    [global::ABI.Automerge.Windows.SyncStateRcwFactory]
    [global::WinRT.ProjectedRuntimeClass(typeof(ISyncState))]
    public sealed class SyncState : global::System.Runtime.InteropServices.ICustomQueryInterface, IWinRTObject, IEquatable<SyncState>
    {
        private IntPtr ThisPtr => _inner == null ? (((IWinRTObject)this).NativeObject).ThisPtr : _inner.ThisPtr;

        private readonly IObjectReference _inner = null;



        private IObjectReference _objRef_global__Automerge_Windows_ISyncState => _inner;


        private static volatile IObjectReference ___objRef_global__Automerge_Windows_SyncState;
        private static IObjectReference _objRef_global__Automerge_Windows_SyncState
        {
            get
            { 
                var factory = ___objRef_global__Automerge_Windows_SyncState;
                if (factory != null && factory.IsInCurrentContext)
                {
                    return factory;
                }
                else
                {
                    return ___objRef_global__Automerge_Windows_SyncState = ActivationFactory.Get("Automerge.Windows.SyncState");
                }
            }
        }

        public SyncState() 
        {
            _inner = global::ABI.WinRT.Interop.IActivationFactoryMethods.ActivateInstanceUnsafe(_objRef_global__Automerge_Windows_SyncState, global::ABI.Automerge.Windows.ISyncStateMethods.IID);
            ComWrappersSupport.RegisterObjectForInterface(this, ThisPtr);
            ComWrappersHelper.Init(_inner, false);

        }

        public static I As<I>() => ActivationFactory.Get("Automerge.Windows.SyncState").AsInterface<I>();

        private static volatile IObjectReference ___objRef_global__Automerge_Windows_ISyncStateStatics;
        private static IObjectReference _objRef_global__Automerge_Windows_ISyncStateStatics
        {
            get
            { 
                var factory = ___objRef_global__Automerge_Windows_ISyncStateStatics;
                if (factory != null && factory.IsInCurrentContext)
                {
                    return factory;
                }
                else
                {
                    return ___objRef_global__Automerge_Windows_ISyncStateStatics = ActivationFactory.Get("Automerge.Windows.SyncState", global::ABI.Automerge.Windows.ISyncStateStaticsMethods.IID);
                }
            }
        }

        public static SyncState Load(global::Windows.Storage.Streams.IBuffer data) => global::ABI.Automerge.Windows.ISyncStateStaticsMethods.Load(_objRef_global__Automerge_Windows_ISyncStateStatics, data);

        public static SyncState FromAbi(IntPtr thisPtr)
        {
            if (thisPtr == IntPtr.Zero) return null;
            return MarshalInspectable<SyncState>.FromAbi(thisPtr);
        }

        internal SyncState(IObjectReference objRef)
        {
            _inner = objRef.As(global::ABI.Automerge.Windows.ISyncStateMethods.IID);

        }


        public static bool operator ==(SyncState x, SyncState y) => (x?.ThisPtr ?? IntPtr.Zero) == (y?.ThisPtr ?? IntPtr.Zero);
        public static bool operator !=(SyncState x, SyncState y) => !(x == y);
        public bool Equals(SyncState other) => this == other;
        public override bool Equals(object obj) => obj is SyncState that && this == that;
        public override int GetHashCode() => ThisPtr.GetHashCode();


        bool IWinRTObject.HasUnwrappableNativeObject => true;
        IObjectReference IWinRTObject.NativeObject => _inner;
        private volatile global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, IObjectReference> _queryInterfaceCache;
        private global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, IObjectReference> MakeQueryInterfaceCache()
        {
            global::System.Threading.Interlocked.CompareExchange(ref _queryInterfaceCache, new global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, IObjectReference>(), null); 
            return _queryInterfaceCache;
        }
        global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, IObjectReference> IWinRTObject.QueryInterfaceCache => _queryInterfaceCache ?? MakeQueryInterfaceCache();
        private volatile global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, object> _additionalTypeData;
        private global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, object> MakeAdditionalTypeData()
        {
            global::System.Threading.Interlocked.CompareExchange(ref _additionalTypeData, new global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, object>(), null); 
            return _additionalTypeData;
        }
        global::System.Collections.Concurrent.ConcurrentDictionary<RuntimeTypeHandle, object> IWinRTObject.AdditionalTypeData => _additionalTypeData ?? MakeAdditionalTypeData();

        private struct InterfaceTag<I>{};


        public global::Windows.Storage.Streams.IBuffer GenerateSyncMessage(Document doc) => global::ABI.Automerge.Windows.ISyncStateMethods.GenerateSyncMessage(_objRef_global__Automerge_Windows_ISyncState, doc);

        public void ReceiveSyncMessage(Document doc, global::Windows.Storage.Streams.IBuffer message) => global::ABI.Automerge.Windows.ISyncStateMethods.ReceiveSyncMessage(_objRef_global__Automerge_Windows_ISyncState, doc, message);

        public global::Windows.Storage.Streams.IBuffer Save() => global::ABI.Automerge.Windows.ISyncStateMethods.Save(_objRef_global__Automerge_Windows_ISyncState);

        private bool IsOverridableInterface(Guid iid) => false;

        global::System.Runtime.InteropServices.CustomQueryInterfaceResult global::System.Runtime.InteropServices.ICustomQueryInterface.GetInterface(ref Guid iid, out IntPtr ppv)
        {
            ppv = IntPtr.Zero;
            if (IsOverridableInterface(iid) || global::WinRT.Interop.IID.IID_IInspectable == iid)
            {
                return global::System.Runtime.InteropServices.CustomQueryInterfaceResult.NotHandled;
            }

            if (((IWinRTObject)this).NativeObject.TryAs(iid, out ppv) >= 0)
            {
                return global::System.Runtime.InteropServices.CustomQueryInterfaceResult.Handled;
            }

            return global::System.Runtime.InteropServices.CustomQueryInterfaceResult.NotHandled;
        }
    }
}

#pragma warning disable CA1416
namespace ABI.Automerge.Windows
{
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public struct Document
    {

        public static IObjectReference CreateMarshaler(global::Automerge.Windows.Document obj) => obj is null ? null : MarshalInspectable<global::Automerge.Windows.Document>.CreateMarshaler<IUnknownVftbl>(obj, global::ABI.Automerge.Windows.IDocumentMethods.IID);
        public static ObjectReferenceValue CreateMarshaler2(global::Automerge.Windows.Document obj) => MarshalInspectable<object>.CreateMarshaler2(obj, global::ABI.Automerge.Windows.IDocumentMethods.IID);
        public static IntPtr GetAbi(IObjectReference value) => value is null ? IntPtr.Zero : MarshalInterfaceHelper<object>.GetAbi(value);
        public static global::Automerge.Windows.Document FromAbi(IntPtr thisPtr) => global::Automerge.Windows.Document.FromAbi(thisPtr);
        public static IntPtr FromManaged(global::Automerge.Windows.Document obj) => obj is null ? IntPtr.Zero : CreateMarshaler2(obj).Detach();
        public static unsafe MarshalInterfaceHelper<global::Automerge.Windows.Document>.MarshalerArray CreateMarshalerArray(global::Automerge.Windows.Document[] array) => MarshalInterfaceHelper<global::Automerge.Windows.Document>.CreateMarshalerArray2(array, (o) => CreateMarshaler2(o));
        public static (int length, IntPtr data) GetAbiArray(object box) => MarshalInterfaceHelper<global::Automerge.Windows.Document>.GetAbiArray(box);
        public static unsafe global::Automerge.Windows.Document[] FromAbiArray(object box) => MarshalInterfaceHelper<global::Automerge.Windows.Document>.FromAbiArray(box, FromAbi);
        public static void CopyAbiArray(global::Automerge.Windows.Document[] array, object box) => MarshalInterfaceHelper<global::Automerge.Windows.Document>.CopyAbiArray(array, box, FromAbi);
        public static (int length, IntPtr data) FromManagedArray(global::Automerge.Windows.Document[] array) => MarshalInterfaceHelper<global::Automerge.Windows.Document>.FromManagedArray(array, (o) => FromManaged(o));
        public static void DisposeMarshaler(IObjectReference value) => MarshalInspectable<object>.DisposeMarshaler(value);
        public static void DisposeMarshalerArray(MarshalInterfaceHelper<global::Automerge.Windows.Document>.MarshalerArray array) => MarshalInterfaceHelper<global::Automerge.Windows.Document>.DisposeMarshalerArray(array);
        public static void DisposeAbi(IntPtr abi) => MarshalInspectable<object>.DisposeAbi(abi);
        public static unsafe void DisposeAbiArray(object box) => MarshalInspectable<object>.DisposeAbiArray(box);
    }
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal sealed class DocumentRcwFactoryAttribute : global::WinRT.WinRTImplementationTypeRcwFactoryAttribute
    {
        public override object CreateInstance(global::WinRT.IInspectable inspectable)
            => new global::Automerge.Windows.Document(inspectable.ObjRef);
    }
    internal static class IDocumentMethods
    {


        internal static unsafe global::Windows.Storage.Streams.IBuffer Save(IObjectReference _obj)
        {
            var ThisPtr = _obj.ThisPtr;

            IntPtr __retval = default;
            try
            {
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr*, int>**)ThisPtr)[6](ThisPtr, &__retval));
                global::System.GC.KeepAlive(_obj);
                return MarshalInterface<global::Windows.Storage.Streams.IBuffer>.FromAbi(__retval);
            }
            finally
            {
                MarshalInterface<global::Windows.Storage.Streams.IBuffer>.DisposeAbi(__retval);
            }
        }

        internal static unsafe global::Windows.Storage.Streams.IBuffer GetHeads(IObjectReference _obj)
        {
            var ThisPtr = _obj.ThisPtr;

            IntPtr __retval = default;
            try
            {
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr*, int>**)ThisPtr)[7](ThisPtr, &__retval));
                global::System.GC.KeepAlive(_obj);
                return MarshalInterface<global::Windows.Storage.Streams.IBuffer>.FromAbi(__retval);
            }
            finally
            {
                MarshalInterface<global::Windows.Storage.Streams.IBuffer>.DisposeAbi(__retval);
            }
        }

        internal static unsafe global::Windows.Storage.Streams.IBuffer GetChanges(IObjectReference _obj, global::Windows.Storage.Streams.IBuffer heads)
        {
            var ThisPtr = _obj.ThisPtr;

            ObjectReferenceValue __heads = default;
            IntPtr __retval = default;
            try
            {
                __heads = MarshalInterface<global::Windows.Storage.Streams.IBuffer>.CreateMarshaler2(heads, global::ABI.Windows.Storage.Streams.IBufferMethods.IID);
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr, IntPtr*, int>**)ThisPtr)[8](ThisPtr, MarshalInspectable<object>.GetAbi(__heads), &__retval));
                global::System.GC.KeepAlive(_obj);
                return MarshalInterface<global::Windows.Storage.Streams.IBuffer>.FromAbi(__retval);
            }
            finally
            {
                MarshalInspectable<object>.DisposeMarshaler(__heads);
                MarshalInterface<global::Windows.Storage.Streams.IBuffer>.DisposeAbi(__retval);
            }
        }

        internal static unsafe void ApplyChanges(IObjectReference _obj, global::Windows.Storage.Streams.IBuffer changes)
        {
            var ThisPtr = _obj.ThisPtr;

            ObjectReferenceValue __changes = default;
            try
            {
                __changes = MarshalInterface<global::Windows.Storage.Streams.IBuffer>.CreateMarshaler2(changes, global::ABI.Windows.Storage.Streams.IBufferMethods.IID);
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr, int>**)ThisPtr)[9](ThisPtr, MarshalInspectable<object>.GetAbi(__changes)));
                global::System.GC.KeepAlive(_obj);
            }
            finally
            {
                MarshalInspectable<object>.DisposeMarshaler(__changes);
            }
        }

        internal static unsafe void Merge(IObjectReference _obj, global::Automerge.Windows.Document other)
        {
            var ThisPtr = _obj.ThisPtr;

            ObjectReferenceValue __other = default;
            try
            {
                __other = global::ABI.Automerge.Windows.Document.CreateMarshaler2(other);
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr, int>**)ThisPtr)[10](ThisPtr, MarshalInspectable<object>.GetAbi(__other)));
                global::System.GC.KeepAlive(_obj);
            }
            finally
            {
                MarshalInspectable<object>.DisposeMarshaler(__other);
            }
        }

        internal static unsafe string GetValue(IObjectReference _obj, string pathJson)
        {
            var ThisPtr = _obj.ThisPtr;

            IntPtr __retval = default;
            try
            {
                MarshalString.Pinnable __pathJson = new(pathJson);
                fixed(void* ___pathJson = __pathJson)
                {
                    global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr, IntPtr*, int>**)ThisPtr)[11](ThisPtr, MarshalString.GetAbi(ref __pathJson), &__retval));
                    global::System.GC.KeepAlive(_obj);
                    return MarshalString.FromAbi(__retval);
                }
            }
            finally
            {
                MarshalString.DisposeAbi(__retval);
            }
        }

        internal static unsafe void PutJsonRoot(IObjectReference _obj, string jsonObj)
        {
            var ThisPtr = _obj.ThisPtr;

            MarshalString.Pinnable __jsonObj = new(jsonObj);
            fixed(void* ___jsonObj = __jsonObj)
            {
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr, int>**)ThisPtr)[12](ThisPtr, MarshalString.GetAbi(ref __jsonObj)));
                global::System.GC.KeepAlive(_obj);
            }
        }


        public static ref readonly global::System.Guid IID
        {
            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            get
            {
                global::System.ReadOnlySpan<byte> data = new byte[] { 0x60, 0xD0, 0x38, 0x21, 0xF9, 0xE4, 0x86, 0x5C, 0xB4, 0xD5, 0x28, 0x38, 0x69, 0x91, 0xF7, 0xAA };
                return ref global::System.Runtime.CompilerServices.Unsafe.As<byte, global::System.Guid>(ref global::System.Runtime.InteropServices.MemoryMarshal.GetReference(data));
            }
        }

    }
    [Guid("2138D060-E4F9-5C86-B4D5-28386991F7AA")]
    internal interface IDocument : global::Automerge.Windows.IDocument
    {
    }
    internal static class IDocumentStaticsMethods
    {


        internal static unsafe global::Automerge.Windows.Document Load(IObjectReference _obj, global::Windows.Storage.Streams.IBuffer data)
        {
            var ThisPtr = _obj.ThisPtr;

            ObjectReferenceValue __data = default;
            IntPtr __retval = default;
            try
            {
                __data = MarshalInterface<global::Windows.Storage.Streams.IBuffer>.CreateMarshaler2(data, global::ABI.Windows.Storage.Streams.IBufferMethods.IID);
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr, IntPtr*, int>**)ThisPtr)[6](ThisPtr, MarshalInspectable<object>.GetAbi(__data), &__retval));
                global::System.GC.KeepAlive(_obj);
                return global::ABI.Automerge.Windows.Document.FromAbi(__retval);
            }
            finally
            {
                MarshalInspectable<object>.DisposeMarshaler(__data);
                global::ABI.Automerge.Windows.Document.DisposeAbi(__retval);
            }
        }


        public static ref readonly global::System.Guid IID
        {
            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            get
            {
                global::System.ReadOnlySpan<byte> data = new byte[] { 0x15, 0xCE, 0x43, 0x2F, 0x6B, 0xB3, 0x5B, 0x5C, 0xB8, 0xE, 0x66, 0x4, 0x48, 0xDD, 0x51, 0x19 };
                return ref global::System.Runtime.CompilerServices.Unsafe.As<byte, global::System.Guid>(ref global::System.Runtime.InteropServices.MemoryMarshal.GetReference(data));
            }
        }

    }
    [Guid("2F43CE15-B36B-5C5B-B80E-660448DD5119")]
    internal interface IDocumentStatics : global::Automerge.Windows.IDocumentStatics
    {
    }
    internal static class ISyncStateMethods
    {


        internal static unsafe global::Windows.Storage.Streams.IBuffer GenerateSyncMessage(IObjectReference _obj, global::Automerge.Windows.Document doc)
        {
            var ThisPtr = _obj.ThisPtr;

            ObjectReferenceValue __doc = default;
            IntPtr __retval = default;
            try
            {
                __doc = global::ABI.Automerge.Windows.Document.CreateMarshaler2(doc);
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr, IntPtr*, int>**)ThisPtr)[6](ThisPtr, MarshalInspectable<object>.GetAbi(__doc), &__retval));
                global::System.GC.KeepAlive(_obj);
                return MarshalInterface<global::Windows.Storage.Streams.IBuffer>.FromAbi(__retval);
            }
            finally
            {
                MarshalInspectable<object>.DisposeMarshaler(__doc);
                MarshalInterface<global::Windows.Storage.Streams.IBuffer>.DisposeAbi(__retval);
            }
        }

        internal static unsafe void ReceiveSyncMessage(IObjectReference _obj, global::Automerge.Windows.Document doc, global::Windows.Storage.Streams.IBuffer message)
        {
            var ThisPtr = _obj.ThisPtr;

            ObjectReferenceValue __doc = default;
            ObjectReferenceValue __message = default;
            try
            {
                __doc = global::ABI.Automerge.Windows.Document.CreateMarshaler2(doc);
                __message = MarshalInterface<global::Windows.Storage.Streams.IBuffer>.CreateMarshaler2(message, global::ABI.Windows.Storage.Streams.IBufferMethods.IID);
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr, IntPtr, int>**)ThisPtr)[7](ThisPtr, MarshalInspectable<object>.GetAbi(__doc), MarshalInspectable<object>.GetAbi(__message)));
                global::System.GC.KeepAlive(_obj);
            }
            finally
            {
                MarshalInspectable<object>.DisposeMarshaler(__doc);
                MarshalInspectable<object>.DisposeMarshaler(__message);
            }
        }

        internal static unsafe global::Windows.Storage.Streams.IBuffer Save(IObjectReference _obj)
        {
            var ThisPtr = _obj.ThisPtr;

            IntPtr __retval = default;
            try
            {
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr*, int>**)ThisPtr)[8](ThisPtr, &__retval));
                global::System.GC.KeepAlive(_obj);
                return MarshalInterface<global::Windows.Storage.Streams.IBuffer>.FromAbi(__retval);
            }
            finally
            {
                MarshalInterface<global::Windows.Storage.Streams.IBuffer>.DisposeAbi(__retval);
            }
        }


        public static ref readonly global::System.Guid IID
        {
            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            get
            {
                global::System.ReadOnlySpan<byte> data = new byte[] { 0x3, 0xE, 0xBC, 0x60, 0x13, 0x1, 0x2F, 0x51, 0xAE, 0xAC, 0x5D, 0x1A, 0xE5, 0x42, 0xAE, 0x95 };
                return ref global::System.Runtime.CompilerServices.Unsafe.As<byte, global::System.Guid>(ref global::System.Runtime.InteropServices.MemoryMarshal.GetReference(data));
            }
        }

    }
    [Guid("60BC0E03-0113-512F-AEAC-5D1AE542AE95")]
    internal interface ISyncState : global::Automerge.Windows.ISyncState
    {
    }
    internal static class ISyncStateStaticsMethods
    {


        internal static unsafe global::Automerge.Windows.SyncState Load(IObjectReference _obj, global::Windows.Storage.Streams.IBuffer data)
        {
            var ThisPtr = _obj.ThisPtr;

            ObjectReferenceValue __data = default;
            IntPtr __retval = default;
            try
            {
                __data = MarshalInterface<global::Windows.Storage.Streams.IBuffer>.CreateMarshaler2(data, global::ABI.Windows.Storage.Streams.IBufferMethods.IID);
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr, IntPtr*, int>**)ThisPtr)[6](ThisPtr, MarshalInspectable<object>.GetAbi(__data), &__retval));
                global::System.GC.KeepAlive(_obj);
                return global::ABI.Automerge.Windows.SyncState.FromAbi(__retval);
            }
            finally
            {
                MarshalInspectable<object>.DisposeMarshaler(__data);
                global::ABI.Automerge.Windows.SyncState.DisposeAbi(__retval);
            }
        }


        public static ref readonly global::System.Guid IID
        {
            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            get
            {
                global::System.ReadOnlySpan<byte> data = new byte[] { 0x64, 0x21, 0xEF, 0xBA, 0x63, 0xC7, 0xDF, 0x5C, 0xB0, 0xDB, 0x88, 0x3C, 0xD7, 0x61, 0xB6, 0xCC };
                return ref global::System.Runtime.CompilerServices.Unsafe.As<byte, global::System.Guid>(ref global::System.Runtime.InteropServices.MemoryMarshal.GetReference(data));
            }
        }

    }
    [Guid("BAEF2164-C763-5CDF-B0DB-883CD761B6CC")]
    internal interface ISyncStateStatics : global::Automerge.Windows.ISyncStateStatics
    {
    }
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public struct SyncState
    {

        public static IObjectReference CreateMarshaler(global::Automerge.Windows.SyncState obj) => obj is null ? null : MarshalInspectable<global::Automerge.Windows.SyncState>.CreateMarshaler<IUnknownVftbl>(obj, global::ABI.Automerge.Windows.ISyncStateMethods.IID);
        public static ObjectReferenceValue CreateMarshaler2(global::Automerge.Windows.SyncState obj) => MarshalInspectable<object>.CreateMarshaler2(obj, global::ABI.Automerge.Windows.ISyncStateMethods.IID);
        public static IntPtr GetAbi(IObjectReference value) => value is null ? IntPtr.Zero : MarshalInterfaceHelper<object>.GetAbi(value);
        public static global::Automerge.Windows.SyncState FromAbi(IntPtr thisPtr) => global::Automerge.Windows.SyncState.FromAbi(thisPtr);
        public static IntPtr FromManaged(global::Automerge.Windows.SyncState obj) => obj is null ? IntPtr.Zero : CreateMarshaler2(obj).Detach();
        public static unsafe MarshalInterfaceHelper<global::Automerge.Windows.SyncState>.MarshalerArray CreateMarshalerArray(global::Automerge.Windows.SyncState[] array) => MarshalInterfaceHelper<global::Automerge.Windows.SyncState>.CreateMarshalerArray2(array, (o) => CreateMarshaler2(o));
        public static (int length, IntPtr data) GetAbiArray(object box) => MarshalInterfaceHelper<global::Automerge.Windows.SyncState>.GetAbiArray(box);
        public static unsafe global::Automerge.Windows.SyncState[] FromAbiArray(object box) => MarshalInterfaceHelper<global::Automerge.Windows.SyncState>.FromAbiArray(box, FromAbi);
        public static void CopyAbiArray(global::Automerge.Windows.SyncState[] array, object box) => MarshalInterfaceHelper<global::Automerge.Windows.SyncState>.CopyAbiArray(array, box, FromAbi);
        public static (int length, IntPtr data) FromManagedArray(global::Automerge.Windows.SyncState[] array) => MarshalInterfaceHelper<global::Automerge.Windows.SyncState>.FromManagedArray(array, (o) => FromManaged(o));
        public static void DisposeMarshaler(IObjectReference value) => MarshalInspectable<object>.DisposeMarshaler(value);
        public static void DisposeMarshalerArray(MarshalInterfaceHelper<global::Automerge.Windows.SyncState>.MarshalerArray array) => MarshalInterfaceHelper<global::Automerge.Windows.SyncState>.DisposeMarshalerArray(array);
        public static void DisposeAbi(IntPtr abi) => MarshalInspectable<object>.DisposeAbi(abi);
        public static unsafe void DisposeAbiArray(object box) => MarshalInspectable<object>.DisposeAbiArray(box);
    }
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal sealed class SyncStateRcwFactoryAttribute : global::WinRT.WinRTImplementationTypeRcwFactoryAttribute
    {
        public override object CreateInstance(global::WinRT.IInspectable inspectable)
            => new global::Automerge.Windows.SyncState(inspectable.ObjRef);
    }
}
#pragma warning restore CA1416
