// dll_exports.cpp — Standard DLL activation exports for WinRT in-process server.
//
// module.g.cpp (generated by cppwinrt) defines WINRT_GetActivationFactory and
// WINRT_CanUnloadNow using the C++/WinRT 2.0 ABI.  Windows Runtime / COM
// expects legacy-named exports DllGetActivationFactory / DllCanUnloadNow.
// These thin forwarding functions bridge the two conventions.
//
// NOTE: Do NOT include pch.h here — it pulls in <windows.h> → combaseapi.h
// which already declares DllCanUnloadNow with a possibly-conflicting linkage.
// Including <stdint.h> is enough: HRESULT and int32_t share the same binary
// representation on Windows (both are 32-bit signed integers).

#include <stdint.h>

// Forward declarations of cppwinrt 2.0 internal symbols (defined in module.g.obj).
// These are declared extern "C" in winrt/base.h so the symbols are undecorated.
extern "C" {
    int32_t __stdcall WINRT_GetActivationFactory(void* classId, void** factory) noexcept;
    int32_t __stdcall WINRT_CanUnloadNow() noexcept;
}

extern "C" {

__declspec(dllexport)
int32_t __stdcall DllGetActivationFactory(void* classId, void** factory) noexcept
{
    return WINRT_GetActivationFactory(classId, factory);
}

__declspec(dllexport)
int32_t __stdcall DllCanUnloadNow() noexcept
{
    return WINRT_CanUnloadNow();
}

} // extern "C"
