// Document.h — WinRT runtime class implementation header.
#pragma once

#include "pch.h"
#include "Helpers.hpp"
// Generated by cppwinrt (run: cppwinrt.exe -in Automerge.Windows.winmd -out .)
// For now we declare the implementation directly.
#include "winrt/Automerge.Windows.h"
#include "Automerge.Windows.g.h"

namespace winrt::Automerge::Windows::implementation {

/// WinRT implementation of the Document runtime class.
struct Document : DocumentT<Document>
{
    Document();

    // Persistence
    Windows::Storage::Streams::IBuffer Save();
    static Automerge::Windows::Document Load(
        Windows::Storage::Streams::IBuffer const& data);

    // Heads
    Windows::Storage::Streams::IBuffer GetHeads();

    // Changes
    Windows::Storage::Streams::IBuffer GetChanges(
        Windows::Storage::Streams::IBuffer const& heads);
    void ApplyChanges(Windows::Storage::Streams::IBuffer const& changes);

    // Merge
    void Merge(Automerge::Windows::Document const& other);

    // Read
    hstring GetValue(hstring const& pathJson);

    // Write
    void PutJsonRoot(hstring const& jsonObj);

    // Internal access for SyncState
    ::automerge::Document& native_doc() noexcept { return doc_; }

private:
    ::automerge::Document doc_;
};

} // namespace winrt::Automerge::Windows::implementation

namespace winrt::Automerge::Windows::factory_implementation {
struct Document : DocumentT<Document, implementation::Document> {};
} // namespace winrt::Automerge::Windows::factory_implementation
